name: Contract Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
      working-directory: ./contracts
    
    - name: Install packages
      run: yarn install --frozen-lockfile
      working-directory: ./contracts
    
    - name: Build project
      run: npx hardhat compile
    
    - name: Run tests
      run: npx hardhat test